import type { AppState, Progress, QuizConfig, Settings } from "./types";

export const ACCENTS: { id: string; label: string; value: string; glow: string }[] = [
  { id: "ember", label: "Ember", value: "oklch(0.72 0.18 48)", glow: "oklch(0.82 0.16 72)" },
  { id: "cyan", label: "Arc Cyan", value: "oklch(0.72 0.14 205)", glow: "oklch(0.82 0.12 195)" },
  { id: "lime", label: "Acid Lime", value: "oklch(0.78 0.18 130)", glow: "oklch(0.86 0.16 140)" },
  { id: "violet", label: "Ion Violet", value: "oklch(0.68 0.18 300)", glow: "oklch(0.78 0.16 315)" },
  { id: "rose", label: "Signal Rose", value: "oklch(0.68 0.19 15)", glow: "oklch(0.78 0.16 30)" },
];

export const DECK_COLORS = [
  "oklch(0.72 0.18 48)",
  "oklch(0.72 0.14 205)",
  "oklch(0.7 0.15 155)",
  "oklch(0.68 0.18 300)",
  "oklch(0.68 0.19 15)",
  "oklch(0.8 0.15 85)",
];

export const DEFAULT_QUIZ_CONFIG: QuizConfig = {
  deckIds: [],
  questionCount: 10,
  types: [
    "multiple-choice",
    "true-false",
    "fill-blank",
    "short-answer",
    "flashcard",
    "ordering",
    "matching",
    "word-bank",
  ],
  difficulties: ["easy", "medium", "hard"],
  shuffle: true,
  perQuestionSeconds: null,
  totalMinutes: null,
  unlimited: false,
  passingScore: 70,
  xpEnabled: true,
  instantFeedback: true,
  reviewMode: false,
};

export const DEFAULT_SETTINGS: Settings = {
  displayName: "Scholar",
  gradeLevel: "",
  school: "",
  avatarEmoji: "🔥",
  focusSubjects: [],
  studyReason: "",
  dailyGoal: 20,
  confirmBeforeExit: true,
  theme: "dark",
  accent: "ember",
  wallpaper: null,
  wallpaperOpacity: 0.35,
  wallpaperBlur: 4,
  fontScale: 1,
  density: "cozy",
  radius: 0.75,
  buttonSize: "default",
  animationSpeed: 1,
  showProgressBars: true,
  sidebarCollapsed: false,
  reducedMotion: false,
  highContrast: false,
  colorblindPalette: false,
  focusIndicators: true,
  timerMultiplier: 1,
  autoReveal: false,
  shuffleStudy: false,
  showHints: true,
  showExplanations: true,
  defaultQuizConfig: DEFAULT_QUIZ_CONFIG,
  quizWidgets: {
    progress: true,
    timer: true,
    questionNumber: true,
    accuracy: true,
    score: true,
    xp: true,
    combo: true,
    remaining: true,
    difficulty: true,
    concept: true,
  },
  xpEnabled: true,
  achievementPopups: true,
  soundEnabled: false,
  dashboardWidgets: [
    "continue",
    "goal",
    "level",
    "streak",
    "due",
    "activity",
    "weak",
    "decks",
    "achievements",
    "stats",
  ],
  hiddenWidgets: [],
  devMode: false,
};

export const DEFAULT_PROGRESS: Progress = {
  xp: 0,
  lifetimeXp: 0,
  totalAnswered: 0,
  totalCorrect: 0,
  totalIncorrect: 0,
  totalSkipped: 0,
  studyTimeMs: 0,
  streak: 0,
  longestStreak: 0,
  lastStudyDay: null,
  studyDays: {},
  unlockedAchievements: [],
  perfectQuizzes: 0,
  quizzesCompleted: 0,
  bestAccuracy: 0,
  bestCombo: 0,
  conceptStats: {},
};

export const DEFAULT_STATE: AppState = {
  version: 1,
  onboardingComplete: false,
  decks: [],
  settings: DEFAULT_SETTINGS,
  progress: DEFAULT_PROGRESS,
  history: [],
  results: [],
  templates: [],
};

export const GRADE_LEVELS = [
  "Middle school",
  "Grade 9",
  "Grade 10",
  "Grade 11",
  "Grade 12",
  "Undergraduate",
  "Postgraduate",
  "Professional / certification",
  "Self-directed learner",
];

export const SUBJECT_SUGGESTIONS = [
  "Mathematics",
  "Biology",
  "Chemistry",
  "Physics",
  "History",
  "Geography",
  "Literature",
  "Languages",
  "Computer Science",
  "Economics",
  "Law",
  "Medicine",
];

export const AVATAR_EMOJIS = ["🔥", "🧠", "📚", "⚡", "🦉", "🚀", "🧪", "🎯", "🐝", "🌙"];

export const STUDY_REASONS = [
  "Exam prep",
  "Daily revision",
  "Certification",
  "Curiosity",
];