/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ImportRouteImport } from './routes/import'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FormatRouteImport } from './routes/format'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as StudyDeckIdRouteImport } from './routes/study.$deckId'
import { Route as DecksDeckIdRouteImport } from './routes/decks.$deckId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatRoute = FormatRouteImport.update({
  id: '/format',
  path: '/format',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyDeckIdRoute = StudyDeckIdRouteImport.update({
  id: '/study/$deckId',
  path: '/study/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRoute = DecksDeckIdRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/format': typeof FormatRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/stats': typeof StatsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/format': typeof FormatRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/stats': typeof StatsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/decks': typeof DecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/format': typeof FormatRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/stats': typeof StatsRoute
  '/decks/$deckId': typeof DecksDeckIdRoute
  '/study/$deckId': typeof StudyDeckIdRoute
  '/decks/': typeof DecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/format'
    | '/generate'
    | '/import'
    | '/onboarding'
    | '/quiz'
    | '/stats'
    | '/decks/$deckId'
    | '/study/$deckId'
    | '/decks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/format'
    | '/generate'
    | '/import'
    | '/onboarding'
    | '/quiz'
    | '/stats'
    | '/decks/$deckId'
    | '/study/$deckId'
    | '/decks'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/format'
    | '/generate'
    | '/import'
    | '/onboarding'
    | '/quiz'
    | '/stats'
    | '/decks/$deckId'
    | '/study/$deckId'
    | '/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  FormatRoute: typeof FormatRoute
  GenerateRoute: typeof GenerateRoute
  ImportRoute: typeof ImportRoute
  OnboardingRoute: typeof OnboardingRoute
  QuizRoute: typeof QuizRoute
  StatsRoute: typeof StatsRoute
  DecksDeckIdRoute: typeof DecksDeckIdRoute
  StudyDeckIdRoute: typeof StudyDeckIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/format': {
      id: '/format'
      path: '/format'
      fullPath: '/format'
      preLoaderRoute: typeof FormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$deckId': {
      id: '/study/$deckId'
      path: '/study/$deckId'
      fullPath: '/study/$deckId'
      preLoaderRoute: typeof StudyDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  FormatRoute: FormatRoute,
  GenerateRoute: GenerateRoute,
  ImportRoute: ImportRoute,
  OnboardingRoute: OnboardingRoute,
  QuizRoute: QuizRoute,
  StatsRoute: StatsRoute,
  DecksDeckIdRoute: DecksDeckIdRoute,
  StudyDeckIdRoute: StudyDeckIdRoute,
  DecksIndexRoute: DecksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
